### ISSUE TITLE
Can't exclude 1 currency (0 and more than 1 work)

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#92]
Try these gets:
~~~
http://localhost:3000/arbitrageData/AUD/CHF/5?exclude=USD
http://localhost:3000/arbitrageData/AUD/CHF/5?exclude=USD&
http://localhost:3000/arbitrageData/AUD/CHF/5?exclude=USD&eclude=JPY
~~~

**Comment by james-nakashian** [comment]
I've fixed this on the modified_endpoints branch.
This issue was that when only 1 currency was being excluded, the argument was a string, not an array, so it failed the IsArray check.
The endpoint now checks if its a string first, then if its an array, before deciding that the argument is incorrect.

**Comment by jmorgancusick** [comment]
Completed as of 036a9980e14decb863106e4fe1b666530ac63283.
